---
# handlers file for rabbitmq
- name: stop rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: stopped

- name: rabbitmq-server-reload
  systemd:
    name: rabbitmq-server
    daemon_reload: yes

- name: start rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: started

- name: restart rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: restarted

- name: restart awslogd
  systemd:
    name: awslogsd
    state: restarted
